# Generated by Django 4.2.3 on 2023-07-15 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_app", "0002_quizquestions_topic_delete_quiz_quizquestions_topic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuizQuestions",
            new_name="QuizQuestion",
        ),
    ]
