# Generated by Django 4.2.3 on 2023-07-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_app", "0004_competitionentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("options", models.TextField()),
                ("correct_answer", models.CharField(max_length=255)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz_app.topic"
                    ),
                ),
            ],
        ),
    ]
